CREATE TABLE GRD_EX_USER (
    USER_ID         BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
    USER_EMAIL      VARCHAR(255) NOT NULL UNIQUE,
    USER_PASSWORD   VARCHAR(100) NOT NULL,
    USER_ROLE       VARCHAR(100)
);