CREATE TABLE GRD_EX_CHAPTERS (
    CHAPTER_ID BIGSERIAL PRIMARY KEY,
    CHAPTER_TITLE VARCHAR(255) NOT NULL,
    CHAPTER_DESC TEXT
);

CREATE TABLE GRD_EX_QUESTION (
    QUESTION_ID BIGSERIAL PRIMARY KEY,
    CHAPTER_ID BIGINT NOT NULL,
    QUESTION_TYPE VARCHAR(255) NOT NULL,
    QUESTION_CONTENT jsonb,

    CONSTRAINT check_question_type CHECK (QUESTION_TYPE IN ('FILL_IN_THE_BLANK', 'MULTIPLE_CHOICE', 'DRAG_AND_DROP')),

    CONSTRAINT fk_chapter
        FOREIGN KEY(CHAPTER_ID)
        REFERENCES GRD_EX_CHAPTERS(CHAPTER_ID)
);

CREATE TABLE GRD_EX_USER_ANSWER (
    USER_ANSWER_ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    QUESTION_ID BIGINT NOT NULL,
    IS_CORRECT BOOLEAN NOT NULL,
    ANSWERED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_user
        FOREIGN KEY(USER_ID)
        REFERENCES GRD_EX_USER(USER_ID),
    CONSTRAINT fk_question
        FOREIGN KEY(QUESTION_ID)
        REFERENCES GRD_EX_QUESTION(QUESTION_ID)
);