ALTER TABLE GRD_EX_USER
ADD COLUMN USER_NAME VARCHAR(255),
ADD COLUMN USER_CREATED_AT TIMESTAMP WITHOUT TIME ZONE;

UPDATE GRD_EX_USER SET USER_CREATED_AT = CURRENT_TIMESTAMP WHERE USER_CREATED_AT IS NULL;

ALTER TABLE GRD_EX_USER ALTER COLUMN USER_CREATED_AT SET NOT NULL;